# Generated by Django 3.2.9 on 2021-11-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Humedad_Suelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Luminosidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Origen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=20)),
                ('Pais', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Tolerancia_Frio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='tipo',
            old_name='nombre',
            new_name='Nombre',
        ),
        migrations.RenameField(
            model_name='ubicacion',
            old_name='especie',
            new_name='Especie',
        ),
        migrations.RenameField(
            model_name='ubicacion',
            old_name='zona',
            new_name='Zona',
        ),
        migrations.RenameField(
            model_name='zona',
            old_name='descripcion',
            new_name='Descripcion',
        ),
        migrations.RenameField(
            model_name='zona',
            old_name='nombre',
            new_name='Nombre',
        ),
    ]
