# Generated by Django 3.2.9 on 2021-11-23 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0002_auto_20211123_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especie',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='especie',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='especie',
            name='nombre_cientifico',
        ),
        migrations.RemoveField(
            model_name='especie',
            name='tipo',
        ),
        migrations.AddField(
            model_name='especie',
            name='Altura',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='especie',
            name='Autor',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='especie',
            name='Estado',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='flora.estado'),
        ),
        migrations.AddField(
            model_name='especie',
            name='Flores',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='especie',
            name='Hojas',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='especie',
            name='Humedad_Suelo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='flora.humedad_suelo'),
        ),
        migrations.AddField(
            model_name='especie',
            name='Imagen',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='flora.imagen'),
        ),
        migrations.AddField(
            model_name='especie',
            name='Imagen_Perfil',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='especie',
            name='Imagen_QR',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='especie',
            name='Latitud',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='especie',
            name='Longitud',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='especie',
            name='Luminosidad',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='flora.luminosidad'),
        ),
        migrations.AddField(
            model_name='especie',
            name='Nombre',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='especie',
            name='Nombre_Cientifico',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='especie',
            name='Origen',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='flora.origen'),
        ),
        migrations.AddField(
            model_name='especie',
            name='QR',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='especie',
            name='Semillas',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='especie',
            name='Tipo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='flora.tipo'),
        ),
        migrations.AddField(
            model_name='especie',
            name='Tolerancia_Frio',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='flora.tolerancia_frio'),
        ),
        migrations.AddField(
            model_name='especie',
            name='Zona',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='flora.zona'),
        ),
    ]
