# Generated by Django 3.2.9 on 2021-11-24 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0005_auto_20211123_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='zona',
            name='Especie',
            field=models.ManyToManyField(through='flora.Ubicacion', to='flora.Especie'),
        ),
        migrations.RemoveField(
            model_name='especie',
            name='Zona',
        ),
        migrations.AddField(
            model_name='especie',
            name='Zona',
            field=models.ManyToManyField(through='flora.Ubicacion', to='flora.Zona'),
        ),
    ]
