# Generated by Django 3.2.9 on 2021-12-01 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0010_alter_zona_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zona',
            name='Descripcion',
            field=models.CharField(max_length=200),
        ),
    ]
