# Generated by Django 3.2.9 on 2021-12-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0011_alter_zona_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='Nombre',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
