# Generated by Django 3.2.9 on 2021-12-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0012_alter_imagen_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especie',
            name='Imagen_Perfil',
            field=models.ImageField(null=True, upload_to='Imagen_Perfil'),
        ),
    ]
