# Generated by Django 3.2.9 on 2021-12-23 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0017_auto_20211214_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especie',
            name='Longitud',
            field=models.CharField(blank=True, default='', max_length=900, null=True),
        ),
    ]
