# Generated by Django 3.2.9 on 2021-12-26 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0018_alter_especie_longitud'),
    ]

    operations = [
        migrations.RenameField(
            model_name='especie',
            old_name='Longitud',
            new_name='Localizacion',
        ),
        migrations.RemoveField(
            model_name='especie',
            name='Latitud',
        ),
    ]
