# Generated by Django 3.2.9 on 2021-12-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0020_auto_20211226_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especie',
            name='QR',
            field=models.CharField(blank=True, default=models.CharField(default='', max_length=50), max_length=200, null=True),
        ),
    ]
