# Generated by Django 3.2.9 on 2021-12-26 22:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0025_alter_especie_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especie',
            name='QR',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
